spring:
  application:
    name: spring-boot2-07
  datasource:
    url: jdbc:mysql://localhost:3306/muzimin
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  druid:
    aop-patterns: com.atguigu.admin.*  #监控SpringBean
    filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
    stat-view-servlet: # 配置监控页功能
      enabled: true
      login-username: admin
      login-password: admin
      resetEnable: false
    web-stat-filter: # 监控web
      enabled: true
      urlPattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    filter:
      stat: # 对上面filters里面的stat的详细配置
        slow-sql-millis: 1000
        logSlowSql: true
        enabled: true
      wall:
        enabled: true
        config:
          drop-table-allow: false

  redis:
    ## 方式一：
    ## url: redis://localhost:6379
    ## 方式二：
    host: localhost
    port: 6379
    ## lettuce/jedis
    client-type: jedis
    jedis:
      pool:
        max-active: 10

mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  ## 全局配置文件可以通过configuration来进行实现
  configuration:
    map-underscore-to-camel-case: true

# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      ## 展示健康状态的详细信息
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true


# info:
#   appName: boot-admin
#   appVersion: 1.0.0
#   mavenProjectName: @project.artifactId@
#   mavenProjectVersion: @project.version@
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
      mavenProjectVersion: "@project.version@"